### ISSUE TITLE
#39 성능 개선 / 렌더링 최적화 - 윈도우 포커싱 시 refetch 실행 옵션 변경

### ISSUE THREAD

**Issue by v-va** [OHPick/FE#125]
### 1. 문제 상황 :
브라우저 화면을 이탈했다가 다시 포커스 할 때 마다 refetch가 일어남

### 2. 해결 방법 :
데이터가 stale 상태일 경우, 윈도우가 포커싱 될 때마다 refetch를 실행하는 옵션인 refetchOnWindowFocus를 이용해 제어

### 3. 코드 :
```js
const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      refetchOnWindowFocus: false,
    },
  },
});
```

**Comment by junvely** [comment]
좋습니당~😄
